export interface CountyData {
  name: string;
  subCounties: string[];
  wards: Record<string, string[]>;
  stations: string[];
  localities: string[]; // For backward compatibility
  postalCodes: { code: string; town: string }[];
}

export const KENYA_ADMIN_DATA: Record<string, CountyData> = {
  "MOMBASA": {
    name: "MOMBASA",
    subCounties: ["CHANGAMWE", "JOMVU", "KISAUNI", "NYALI", "LIKONI", "MVITA"],
    wards: {
      "CHANGAMWE": ["PORT REITZ", "KIPEVU", "AIRPORT", "CHANGAMWE", "CHAANI"],
      "JOMVU": ["JOMVU KUU", "MIRITINI", "MIKINDANI"],
      "KISAUNI": ["MJAMBERE", "JUNDA", "BAMBURI", "MWAKIRUNGE", "MTOPANGA", "MAGOGONI", "SHANZU"],
      "NYALI": ["FRERE TOWN", "ZIWA LA NG'OMBE", "MKOMANI", "KONGOWEA", "KADZANDANI"],
      "LIKONI": ["MTONGWE", "SHIKA ADABU", "BOFU", "LIKONI", "TIMBWANI"],
      "MVITA": ["MJI WA KALE/MAKADARA", "TUDOR", "TONONOKA", "SHIMANZI/GANJONI", "MAJENGO"]
    },
    stations: ["SOUTHERN REGION HQS (CUSTOM HOUSE)", "PORT OPERATIONS"],
    localities: ["MOMBASA ISLAND", "NYALI", "BAMBURI", "LIKONI", "CHANGAMWE"],
    postalCodes: [{ code: "80100", town: "MOMBASA" }]
  },
  "KWALE": {
    name: "KWALE",
    subCounties: ["MSAMBWENI", "LUNGALUNGA", "MATUGA", "KINANGO"],
    wards: {
      "MSAMBWENI": ["GOMBATO BONGWE", "UKUNDA", "KINONDO", "RAMISI"],
      "LUNGALUNGA": ["PONGWE/KIKONENI", "DZOMBO", "MWERENI", "VANGA"],
      "MATUGA": ["TSIMBA GOLINI", "WAA", "TIWI", "KUBO SOUTH", "MKONGANI"],
      "KINANGO": ["NDAVAYA", "PUMA", "KINANGO", "MACKINNON ROAD", "CHENGONI/SAMBURU", "MWAVUMBO", "KASEMENI"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["UKUNDA", "DIANI", "KWALE"],
    postalCodes: [{ code: "80400", town: "UKUNDA" }]
  },
  "KILIFI": {
    name: "KILIFI",
    subCounties: ["KILIFI NORTH", "KILIFI SOUTH", "KALOLENI", "RABAI", "GANZE", "MALINDI", "MAGARINI"],
    wards: {
      "KILIFI NORTH": ["TEZO", "SOKONI", "KIBARANI", "DABASO", "MATSANGONI", "WATAMU", "MNARANI"],
      "KILIFI SOUTH": ["JUNJU", "MWARAKAYA", "SHIMO LA TEWA", "CHASIMBA", "MTEPENI"],
      "KALOLENI": ["MARIAKANI", "KAYAFUNGO", "KALOLENI", "MWANAMWINGA"],
      "RABAI": ["MWAWESA", "RURUMA", "KAMBE/RIBE", "RABAI/KISURUTINI"],
      "GANZE": ["GANZE", "BAMBA", "JARIBUNI", "SOKOKE"],
      "MALINDI": ["JILORE", "KAKUYUNI", "GANDA", "MALINDI TOWN", "SHELLA"],
      "MAGARINI": ["MARAFA", "MAGARINI", "GONGONI", "ADU", "GARASHI", "SABAKI"]
    },
    stations: ["MALINDI"],
    localities: ["MALINDI", "WATAMU", "KILIFI"],
    postalCodes: [{ code: "80200", town: "MALINDI" }]
  },
  "TANA RIVER": {
    name: "TANA RIVER",
    subCounties: ["GARSEN", "GALOLE", "BURA"],
    wards: {
      "GARSEN": ["KIPINI EAST", "GARSEN SOUTH", "KIPINI WEST", "GARSEN CENTRAL", "GARSEN WEST", "GARSEN NORTH"],
      "GALOLE": ["KINAKOMBA", "MIKINDUNI", "CHEWANI", "WAYU"],
      "BURA": ["CHEWELE", "HIRIMANI", "BANGALE", "SALA", "MADOGO"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["HOLA", "GARSEN"],
    postalCodes: [{ code: "70101", town: "HOLA" }]
  },
  "LAMU": {
    name: "LAMU",
    subCounties: ["LAMU EAST", "LAMU WEST"],
    wards: {
      "LAMU EAST": ["FAZA", "KIUNGA", "BASUBA"],
      "LAMU WEST": ["SHELLA", "MKOMANI", "HINDI", "MKUNUMBI", "HONGWE", "WITU", "BAHARI"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["LAMU TOWN", "AMU"],
    postalCodes: [{ code: "80500", town: "LAMU" }]
  },
  "TAITA TAVETA": {
    name: "TAITA TAVETA",
    subCounties: ["TAVETA", "WUNDANYI", "MWATATE", "VOI"],
    wards: {
      "TAVETA": ["CHALA", "MAHOO", "BOMANI", "MBOGHONI", "MATA"],
      "WUNDANYI": ["WUNDANYI/MBALE", "WERUGHA", "WUMING EVERYBODY/KISHUSHE", "MWANDA/MGANGE"],
      "MWATATE": ["RONG'E", "MWATATE", "BURA", "CHAWIA", "WUSI/KISHAMBA"],
      "VOI": ["MBOLOLO", "SAGALLA", "KALOLENI", "MARUNGU", "KASIGAU", "NGOLIA"]
    },
    stations: ["VOI"],
    localities: ["VOI", "WUNDANYI", "MWATATE"],
    postalCodes: [{ code: "80300", town: "VOI" }]
  },
  "GARISSA": {
    name: "GARISSA",
    subCounties: ["GARISSA TOWNSHIP", "BALAMBALA", "LAGDERA", "DADAAB", "FAFI", "IJARA"],
    wards: {
      "GARISSA TOWNSHIP": ["WABERI", "GALBET", "TOWNSHIP", "IFTIN"],
      "BALAMBALA": ["BALAMBALA", "DANYERE", "JARA JARA", "SAKA", "SANKURI"],
      "LAGDERA": ["MODOGASHE", "BENANE", "GOREALE", "MAALIMIN", "SABENA", "BARAKI"],
      "DADAAB": ["DERTU", "DADAAB", "LABASIGALE", "DAMAJALE", "LIBOI", "ABAKAILE"],
      "FAFI": ["BURA", "DEKAHARIA", "JARAJILA", "FAFI", "NANIGHI"],
      "IJARA": ["HULUGHO", "SANGAILU", "IJARA", "MASALANI"]
    },
    stations: ["GARISSA"],
    localities: ["GARISSA", "DADAAB"],
    postalCodes: [{ code: "70100", town: "GARISSA" }]
  },
  "WAJIR": {
    name: "WAJIR",
    subCounties: ["WAJIR NORTH", "WAJIR EAST", "TARBAJ", "WAJIR WEST", "ELDAS", "WAJIR SOUTH"],
    wards: {
      "WAJIR NORTH": ["GURAR", "BUTE", "KORONDILE", "MALKAGUFU", "BATALU", "DANABA", "GODOMA"],
      "WAJIR EAST": ["WAGBERI", "TOWNSHIP", "BARWAGO", "KHOROF/HARAR"],
      "TARBAJ": ["ELBEN", "SARMAN", "TARBAJ", "WARGADUD"],
      "WAJIR WEST": ["ARBAJAHAN", "HADADO/ATHIBOHOL", "ADAMASAJIDE", "GANYURE/WAGALLA"],
      "ELDAS": ["ELDAS", "DELLA", "LAKOLEY SOUTH/BASIR", "ELNUR/TULA TULA"],
      "WAJIR SOUTH": ["BENANE", "BURDER", "DADAJA BULLA", "HABASSWEIN", "LAGBOGHOL SOUTH", "IBRAHIM URE", "DIIF"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["WAJIR TOWN"],
    postalCodes: [{ code: "70200", town: "WAJIR" }]
  },
  "MANDERA": {
    name: "MANDERA",
    subCounties: ["MANDERA WEST", "BANISSA", "MANDERA NORTH", "MANDERA SOUTH", "MANDERA EAST", "LAFEY"],
    wards: {
      "MANDERA WEST": ["TAKABA SOUTH", "TAKABA", "LAGSURE", "DANDU", "GITHER"],
      "BANISSA": ["BANISSA", "DERKHALE", "GUBA", "MALKAMARI", "KILIWEHIRI"],
      "MANDERA NORTH": ["ASHABITO", "GUTICHA", "MOROTHILE", "RHAMU", "RHAMU-DIMTU"],
      "MANDERA SOUTH": ["WARGADUD", "KUTULO", "ELWAK SOUTH", "ELWAK NORTH", "SHIMBIR FATUMA"],
      "MANDERA EAST": ["ARABIA", "TOWNSHIP", "NEBOI", "KHALALIO", "LIBEHIA"],
      "LAFEY": ["SALA", "FINO", "LAFEY", "WARANQARA", "ALANGO GOF"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["MANDERA TOWN"],
    postalCodes: [{ code: "70300", town: "MANDERA" }]
  },
  "MARSABIT": {
    name: "MARSABIT",
    subCounties: ["MOYALE", "NORTH HORR", "SAKU", "LAISAMIS"],
    wards: {
      "MOYALE": ["BUTIYE", "SOLOLO", "HEILLU/MANYATTA", "GOLBO", "MOYALE TOWNSHIP", "URAN", "OBBU"],
      "NORTH HORR": ["DUKANA", "MAIKONA", "TURBI", "NORTH HORR", "ILLERET"],
      "SAKU": ["SAGANTE/JALDESA", "KARARE", "MARSABIT CENTRAL"],
      "LAISAMIS": ["LOIYANGALANI", "KARGI/SOUTH HORR", "KORR/NGURUNIT", "LOGO LOGO", "LAISAMIS"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["MARSABIT TOWN", "MOYALE"],
    postalCodes: [{ code: "60500", town: "MARSABIT" }]
  },
  "ISIOLO": {
    name: "ISIOLO",
    subCounties: ["ISIOLO NORTH", "ISIOLO SOUTH"],
    wards: {
      "ISIOLO NORTH": ["WABERA", "BULLA PESA", "CHARI", "CHERAB", "NGARE MARA", "BURAT", "OLDO/NYIRO"],
      "ISIOLO SOUTH": ["GARBATULLA", "KINNA", "SERICHO"]
    },
    stations: ["ISIOLO"],
    localities: ["ISIOLO TOWN"],
    postalCodes: [{ code: "60300", town: "ISIOLO" }]
  },
  "MERU": {
    name: "MERU",
    subCounties: ["IGEMBE SOUTH", "IGEMBE CENTRAL", "IGEMBE NORTH", "TIGANIA WEST", "TIGANIA EAST", "NORTH IMENTI", "BUURI", "CENTRAL IMENTI", "SOUTH IMENTI"],
    wards: {
      "IGEMBE SOUTH": ["MAUA", "KIEGOI/ANTUBOCHIU", "ATHIRU GAITI", "AKACHIU", "KANUNI"],
      "IGEMBE CENTRAL": ["AKIRANG'ONDU", "ATHIRU RUUJINE", "IGEMBE EAST", "NJIA", "KANGETA"],
      "IGEMBE NORTH": ["ANTUAMBUI", "NTUNENE", "ANTUBETWE KIONGO", "NAATHU", "AMWATHI"],
      "TIGANIA WEST": ["ATHWANA", "AKITHII", "KIANJAI", "NKOMO", "MBEU"],
      "TIGANIA EAST": ["THANGATHA", "MIKINDURI", "KIGUCHWA", "MUTHARA", "KARAMA"],
      "NORTH IMENTI": ["MUNICIPALITY", "NTIMA EAST", "NTIMA WEST", "NYAKI WEST", "NYAKI EAST"],
      "BUURI": ["TIMAU", "KISIMA", "KIIRUA/NAARI", "RUIRI/RWARERA", "KIBIRICHIA"],
      "CENTRAL IMENTI": ["MWANGANTHIA", "ABOTHUGUCHI CENTRAL", "ABOTHUGUCHI WEST", "KIAGU"],
      "SOUTH IMENTI": ["MITUNGUU", "IGOJI EAST", "IGOJI WEST", "ABOGETA EAST", "ABOGETA WEST", "NKUENE"]
    },
    stations: ["MERU"],
    localities: ["MERU TOWN", "MAUA"],
    postalCodes: [{ code: "60200", town: "MERU" }]
  },
  "THARAKA-NITHI": {
    name: "THARAKA-NITHI",
    subCounties: ["MAARA", "CHUKA/IGAMBANG'OMBE", "THARAKA"],
    wards: {
      "MAARA": ["MITHERU", "MUTHAMBI", "MWIMBI", "GANGA", "CHOGORIA"],
      "CHUKA/IGAMBANG'OMBE": ["MARIANI", "KARINGANI", "MAGUMONI", "MUGWE", "IGAMBANG'OMBE"],
      "THARAKA": ["GATUNGA", "MUKOTHIMA", "NKONDI", "CHIAKARIGA", "MARIMANTI"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["CHUKA", "CHOGORIA"],
    postalCodes: [{ code: "60400", town: "CHUKA" }]
  },
  "EMBU": {
    name: "EMBU",
    subCounties: ["MANYATTA", "RUNYENJES", "MBEERE SOUTH", "MBEERE NORTH"],
    wards: {
      "MANYATTA": ["RUGURU/NGANDORI", "KITHIMU", "NGINDA", "MBETI NORTH", "KIRIMARI", "GATURI SOUTH"],
      "RUNYENJES": ["GATURI NORTH", "KAGAARI SOUTH", "CENTRAL  WARD", "KAGAARI NORTH", "KYENI NORTH", "KYENI SOUTH"],
      "MBEERE SOUTH": ["MWEA", "MAKIMA", "MBETI SOUTH", "MAVURIA", "KIAMBERE"],
      "MBEERE NORTH": ["NTHAWA", "MUMINJI", "EVURORE"]
    },
    stations: ["EMBU"],
    localities: ["EMBU TOWN"],
    postalCodes: [{ code: "60100", town: "EMBU" }]
  },
  "KITUI": {
    name: "KITUI",
    subCounties: ["MWINGI NORTH", "MWINGI WEST", "MWINGI CENTRAL", "KITUI WEST", "KITUI RURAL", "KITUI CENTRAL", "KITUI EAST", "KITUI SOUTH"],
    wards: {
      "MWINGI NORTH": ["NGOMENI", "KYUSO", "MUMONI", "TSEIKURU", "THARAKA"],
      "MWINGI WEST": ["KYOME/THAANA", "NGUUTANI", "MIGWANI", "KIOMO/KYETHANI"],
      "MWINGI CENTRAL": ["CENTRAL", "KIVOU", "NGUNI", "NUU", "MUI", "WAITA"],
      "KITUI WEST": ["MUTONGUNI", "KAUWI", "MATINYANI", "KWA MUTONGA/KITHUMULA"],
      "KITUI RURAL": ["KISASI", "MBITINI", "KWAVONZA/YATTA", "KANYANGI"],
      "KITUI CENTRAL": ["MIAMBANI", "TOWNSHIP", "KYANGWITHYA WEST", "MULANGO", "KYANGWITHYA EAST"],
      "KITUI EAST": ["ZOMBE/MWITIKA", "NZAMBANI", "CHULUNI", "VOO/KYAMATU", "ENDAU/MALALANI", "MUTITO/KALIKU"],
      "KITUI SOUTH": ["IKANGA/KYATUNE", "MUTOMO", "MUTHA", "IKUTHA", "KANZIKO", "ATHI"]
    },
    stations: ["KITUI"],
    localities: ["KITUI TOWN", "MWINGI"],
    postalCodes: [{ code: "90200", town: "KITUI" }]
  },
  "MACHAKOS": {
    name: "MACHAKOS",
    subCounties: ["MASINGA", "YATTA", "KANGUNDO", "MATUNGULU", "KATHIANI", "MAVOKO", "MACHAKOS TOWN", "MWALA"],
    wards: {
      "MASINGA": ["KIVAA", "MASINGA CENTRAL", "EKALAKALA", "MUTHESYA", "NDITHINI"],
      "YATTA": ["NDALANI", "MATUU", "KITHIMANI", "IKOMBE", "KATANGI"],
      "KANGUNDO": ["KANGUNDO NORTH", "KANGUNDO CENTRAL", "KANGUNDO EAST", "KANGUNDO WEST"],
      "MATUNGULU": ["TALA", "MATUNGULU NORTH", "MATUNGULU EAST", "MATUNGULU WEST", "KYELENI"],
      "KATHIANI": ["MITABONI", "KATHIANI CENTRAL", "UPPER KAEWA/IVETI", "LOWER KAEWA/KAANI"],
      "MAVOKO": ["ATHI RIVER", "KINANIE", "MUTHWANI", "SYOKIMAU/MULOLONGO"],
      "MACHAKOS TOWN": ["KALAMA", "MUA", "MUTITUNI", "MACHAKOS CENTRAL", "MUMBUNI NORTH", "MUVUTI/KIIMA-KIMWE", "KOLA"],
      "MWALA": ["MBIUNI", "MAKUTANO/ MWALA", "MASII", "MUTHETHENI", "WAMUNYU", "KIBAUNI"]
    },
    stations: ["MACHAKOS", "MAVOKO (ATHI RIVER)"],
    localities: ["MACHAKOS TOWN", "ATHI RIVER", "TALA"],
    postalCodes: [{ code: "90100", town: "MACHAKOS" }]
  },
  "MAKUENI": {
    name: "MAKUENI",
    subCounties: ["MBOONI", "KILOME", "KAITI", "MAKUENI", "KIBWEZI WEST", "KIBWEZI EAST"],
    wards: {
      "MBOONI": ["TULIMANI", "MBOONI", "KITHUNGO/KITUNDU", "KITETA/KISAU", "WAIA-KAKO", "KALAWA"],
      "KILOME": ["KASIKEU", "MUKAA", "KIIMA KIU/KALANZONI"],
      "KAITI": ["UKIA", "KEE", "KILUNGU", "ILIMA"],
      "MAKUENI": ["WOTE", "MUVAU/KIKUOMINI", "MAVINDINI", "KITISE/KITHUKI", "KATHONZWENI", "NZAUI/KILILI/KALAMBA", "MBITINI"],
      "KIBWEZI WEST": ["MAKINDU", "NGUUMO", "KIKUMBULYU NORTH", "KIKUMBULYU SOUTH", "NGUU/MASUMBA", "EMALI/MULALA"],
      "KIBWEZI EAST": ["MASONGALENI", "MTITO ANDEI", "THANGE", "IVINGONI/NZAMBANI"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["WOTE", "MAKINDU"],
    postalCodes: [{ code: "90300", town: "WOTE" }]
  },
  "NYANDARUA": {
    name: "NYANDARUA",
    subCounties: ["KINANGOP", "KIPIPIRI", "OL KALOU", "OL JOROK", "NDARAGWA"],
    wards: {
      "KINANGOP": ["ENGINEER", "GATHARA", "NORTH KINANGOP", "MURUNGARU", "NJABINI\\KIBURU", "NYAKIO", "GITHABAI", "MAGUMU"],
      "KIPIPIRI": ["WANJOHI", "KIPIPIRI", "GETA", "GITHIORO"],
      "OL KALOU": ["KARAU", "KANJUIRI RANGE", "MIRANGINE", "KAIMBAGA", "RURII"],
      "OL JOROK": ["GATHANJI", "GATIMU", "WERU", "CHARAGITA"],
      "NDARAGWA": ["LESHAU/PONDO", "KIRIITA", "CENTRAL", "SHAMATA"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["OL KALOU"],
    postalCodes: [{ code: "20303", town: "OL KALOU" }]
  },
  "NYERI": {
    name: "NYERI",
    subCounties: ["TETU", "KIENI", "MATHIRA", "OTHAYA", "MUKURWEINI", "NYERI TOWN"],
    wards: {
      "TETU": ["DEDAN KIMANTHI", "WAMAGANA", "AGUTHI-GAAKI"],
      "KIENI": ["MWEIGA", "NAROMORU KIAMATHAGA", "MWIYOGO/ENDARASHA", "MUGUNDA", "GATARAKWA", "THEGU RIVER", "KABARU", "GAKAWA"],
      "MATHIRA": ["RUGURU", "MAGUTU", "IRIAINI", "KONYU", "KIRIMUKUYU", "KARATINA TOWN"],
      "OTHAYA": ["MAHIGA", "IRIA-INI", "CHINGA", "KARIMA"],
      "MUKURWEINI": ["GIKONDI", "RUGI", "MUKURWE-INI WEST", "MUKURWE-INI CENTRAL"],
      "NYERI TOWN": ["KIGANJO/MATHARI", "RWARE", "GATITU/MURUGURU", "RURING'U", "KAMAKWA/MUKARO"]
    },
    stations: ["NYERI"],
    localities: ["NYERI TOWN", "KARATINA"],
    postalCodes: [{ code: "10100", town: "NYERI" }]
  },
  "KIRINYAGA": {
    name: "KIRINYAGA",
    subCounties: ["MWEA", "GICHUGU", "NDIA", "KIRINYAGA CENTRAL"],
    wards: {
      "MWEA": ["MUTITHI", "KANGAI", "THIBA", "WAMUMU", "NYANGATI", "MURINDUKO", "GATHIGIRIRI", "TEBERE"],
      "GICHUGU": ["KABARE", "BARAGWI", "NJUKIINI", "NGARIAMA", "KARUMANDI"],
      "NDIA": ["MUKURE", "KIINE", "KARITI"],
      "KIRINYAGA CENTRAL": ["MUTIRA", "KANYEKINI", "KERUGOYA", "INOI"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["KERUGOYA", "SAGANA"],
    postalCodes: [{ code: "10300", town: "KERUGOYA" }]
  },
  "MURANG'A": {
    name: "MURANG'A",
    subCounties: ["KANGEMA", "MATHIOYA", "KIHARU", "KIGUMO", "MARAGWA", "KANDARA", "GATANGA"],
    wards: {
      "KANGEMA": ["KANYENYA-INI", "MUGURU", "RWATHIA"],
      "MATHIOYA": ["GITUGI", "KIRU", "KAMACHARIA"],
      "KIHARU": ["WANGU", "MUGOIRI", "MBIRI", "TOWNSHIP", "MURARANDIA", "GATURI"],
      "KIGUMO": ["KAHUMBU", "MUTHITHI", "KIGUMO", "KANGARI", "KINYONA"],
      "MARAGWA": ["KIMORORI/WEMPA", "MAKUYU", "KAMBITI", "KAMAHUHA", "ICHAGAKI", "NGINDA"],
      "KANDARA": ["NG'ARARIA", "MURUKA", "KAGUNDU-INI", "GAICHANJIRU", "ITHIRU", "RUCHU"],
      "GATANGA": ["ITHANGA", "KAKUZI/MITUBIRI", "MUGUMO-INI", "KIHUMBU-INI", "GATANGA", "KARIARA"]
    },
    stations: ["MURANG'A"],
    localities: ["MURANG'A TOWN"],
    postalCodes: [{ code: "10200", town: "MURANG'A" }]
  },
  "KIAMBU": {
    name: "KIAMBU",
    subCounties: ["GATUNDU SOUTH", "GATUNDU NORTH", "JUJA", "THIKA TOWN", "RUIRU", "GITHUNGURI", "KIAMBU", "KIAMBAA", "KABETE", "KIKUYU", "LIMURU", "LARI"],
    wards: {
      "GATUNDU SOUTH": ["KIAMWANGI", "KIGANJO", "NDARUGU", "NGENDA"],
      "GATUNDU NORTH": ["GITUAMBA", "GITHOBOKONI", "CHANIA", "MANG'U"],
      "JUJA": ["MURERA", "THETA", "JUJA", "WITEITHIE", "KALIMONI"],
      "THIKA TOWN": ["TOWNSHIP", "KAMENU", "HOSPITAL", "GATUANYAGA", "NGOLIBA"],
      "RUIRU": ["GITOTHUA", "BIASHARA", "GATONGORA", "KAHAWA SUKARI", "KAHAWA WENDANI", "KIUU", "MWIKI", "MIHOKO"],
      "GITHUNGURI": ["GITHUNGURI", "GITHIGA", "IKINU", "NGEWA", "KOMOTHAI"],
      "KIAMBU": ["TING'ANG'A", "NDUMBERI", "RIABAI", "TOWNSHIP"],
      "KIAMBAA": ["CIANDA", "KARURI", "NDENDERU", "MUCHATHA", "KIHARA"],
      "KABETE": ["GITARU", "MUGUGA", "NYADHUNA", "KABETE", "UTHIRU"],
      "KIKUYU": ["KARAI", "NACHU", "SIGONA", "KIKUYU", "KINOO"],
      "LIMURU": ["BIBIRIONI", "LIMURU CENTRAL", "NDEIYA", "LIMURU EAST", "NGECHA TIGONI"],
      "LARI": ["KINALE", "KIJABE", "NYANDUMA", "KAMBURU", "LARI/KIRENGA"]
    },
    stations: ["THIKA", "KIAMBU", "RUIRU"],
    localities: ["THIKA", "KIAMBU TOWN", "RUIRU", "KIKUYU", "LIMURU"],
    postalCodes: [{ code: "00900", town: "KIAMBU" }, { code: "01000", town: "THIKA" }]
  },
  "TURKANA": {
    name: "TURKANA",
    subCounties: ["TURKANA NORTH", "TURKANA WEST", "TURKANA CENTRAL", "LOIMA", "TURKANA SOUTH", "TURKANA EAST"],
    wards: {
      "TURKANA NORTH": ["KAERIS", "LAKE ZONE", "LAPUR", "KAALENG/KAIKOR", "KIBISH", "NAKALALE"],
      "TURKANA WEST": ["KAKUMA", "LOPUR", "LETEA", "SONGOT", "KALOBEYEI", "LOKICHOGGIO", "NANAAM"],
      "TURKANA CENTRAL": ["KERIO DELTA", "KANG'ATOTHA", "KALOKOL", "LODWAR TOWNSHIP", "KANAMKEMER"],
      "LOIMA": ["KOTARUK/LOBEI", "TURKWEL", "LOIMA", "LOKIRIAMA/LORENGIPPI"],
      "TURKANA SOUTH": ["KAPUTIR", "KATILU", "LOBOKAT", "KALAPATA", "LOKICHAR"],
      "TURKANA EAST": ["KAPEDO/NAPEITOM", "KATILIA", "LOKORI/KOCHODIN"]
    },
    stations: ["LODWAR"],
    localities: ["LODWAR"],
    postalCodes: [{ code: "30500", town: "LODWAR" }]
  },
  "WEST POKOT": {
    name: "WEST POKOT",
    subCounties: ["West Pokot", "SIGOR", "KACHELIBA", "POKOT SOUTH"],
    wards: {
      "KAPENGURIA": ["RIWO", "KAPENGURIA", "MNAGEI", "SIYOI", "ENDUGH", "SOOK"],
      "SIGOR": ["SEKERR", "MASOOL", "LOMUT", "WEIWEI"],
      "KACHELIBA": ["SUAM", "KODICH", "KASEI", "KAPCHOK", "KIWAWA", "ALALE"],
      "POKOT SOUTH": ["CHEPARERIA", "BATEI", "LELAN", "TAPACH"]
    },
    stations: ["KITALE"],
    localities: ["KAPENGURIA", "MAKUTANO", "SIGOR", "CHEPARERIA"],
    postalCodes: [{ code: "30600", town: "KAPENGURIA" }]
  },
  "SAMBURU": {
    name: "SAMBURU",
    subCounties: ["SAMBURU WEST", "SAMBURU NORTH", "SAMBURU EAST"],
    wards: {
      "SAMBURU WEST": ["LODOKEJEK", "SUGUTA MARMAR", "MARALAL", "LOOSUK", "PORO"],
      "SAMBURU NORTH": ["EL-BARTA", "NACHOLA", "NDOTO", "NYIRO", "ANGATA NANYOKIE", "BAAWA"],
      "SAMBURU EAST": ["WASO", "WAMBA WEST", "WAMBA EAST", "WAMBA NORTH"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["MARALAL"],
    postalCodes: [{ code: "20600", town: "MARALAL" }]
  },
  "TRANS NZOIA": {
    name: "TRANS NZOIA",
    subCounties: ["KWANZA", "ENDEBESS", "SABOTI", "KIMININI", "CHERANGANY"],
    wards: {
      "KWANZA": ["KAPOMBOI", "KWANZA", "KEIYO", "BIDII"],
      "ENDEBESS": ["CHEPCHOINA", "ENDEBESS", "MATUMBEI"],
      "SABOTI": ["KINYORO", "MATISI", "TUWANI", "SABOTI", "MACHEWA"],
      "KIMININI": ["KIMININI", "WAITALUK", "SIRENDE", "HOSPITAL", "SIKHENDU", "NABISWA"],
      "CHERANGANY": ["SINYERERE", "MAKUTANO", "KAPLAMAI", "MOTOSIET", "CHERANGANY/SUWERWA", "CHEPSIRO/KIPTOROR", "SITATUNGA"]
    },
    stations: ["KITALE"],
    localities: ["KITALE TOWN", "KIMININI", "SABOTI"],
    postalCodes: [{ code: "30200", town: "KITALE" }]
  },
  "UASIN GISHU": {
    name: "UASIN GISHU",
    subCounties: ["SOY", "TURBO", "MOIBEN", "AINABKOI", "KAPSERET", "KESSES"],
    wards: {
      "SOY": ["MOI'S BRIDGE", "KAPKURES", "ZIWA", "SEGERO/BARSOMBE", "KIPSOMBA", "SOY", "KUINET/KAPSUSWA"],
      "TURBO": ["NGENYILEL", "TAPSAGOI", "KAMAGUT", "KIPLOMBE", "KAPSAOS", "HURUMA"],
      "MOIBEN": ["TEMBELIO", "SERGOIT", "KARUNA/MEIBEKI", "MOIBEN", "KIMUMU"],
      "AINABKOI": ["KAPSOYA", "KAPTAGAT", "AINABKOI/OLARE"],
      "KAPSERET": ["SIMAT/KAPSERET", "KIPKENYO", "NGERIA", "MEGUN", "LANGAS"],
      "KESSES": ["RACECOURSE", "CHEPTIRET/KIPCHAMO", "TULWET/CHUIYAT", "TARAKWA"]
    },
    stations: ["ELDORET"],
    localities: ["ELDORET"],
    postalCodes: [{ code: "30100", town: "ELDORET" }]
  },
  "ELGEYO-MARAKWET": {
    name: "ELGEYO-MARAKWET",
    subCounties: ["MARAKWET EAST", "MARAKWET WEST", "KEIYO NORTH", "KEIYO SOUTH"],
    wards: {
      "MARAKWET EAST": ["KAPYEGO", "SAMBIRIR", "ENDO", "EMBOBUT / EMBULOT"],
      "MARAKWET WEST": ["LELAN", "SENGWER", "CHERANG'ANY/CHEBORORWA", "MOIBEN/KUSERWO", "KAPSOWAR", "ARROR"],
      "KEIYO NORTH": ["EMSOO", "KAMARINY", "KAPCHEMUTWA", "TAMBACH"],
      "KEIYO SOUTH": ["KAPTARAKWA", "CHEPKORIO", "SOY NORTH", "SOY SOUTH", "KABIEMIT", "METKEI"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["ITEN"],
    postalCodes: [{ code: "30700", town: "ITEN" }]
  },
  "NANDI": {
    name: "NANDI",
    subCounties: ["TINDERET", "ALDAI", "NANDI HILLS", "CHESUMEI", "EMGWEN", "MOSOP"],
    wards: {
      "TINDERET": ["SONGHOR/SOBA", "TINDIRET", "CHEMELIL/CHEMASE", "KAPSIMOTWO"],
      "ALDAI": ["KABWARENG", "TERIK", "KEMELOI-MARABA", "KOBUJOI", "KAPTUMO-KABOI", "KOYO-NDURIO"],
      "NANDI HILLS": ["NANDI HILLS", "CHEPKUNYUK", "OL'LESSOS", "KAPCHORUA"],
      "CHESUMEI": ["CHEMUNDU/KAPNG'ETUNY", "KOSIRAI", "LELMOKWO/NGECHEK", "KAPTEL/KAMOIYWO", "KIPTUYA"],
      "EMGWEN": ["CHEPKUMIA", "KAPKANGANI", "KAPSABET", "KILIBWONI"],
      "MOSOP": ["CHEPTERWAI", "KIPKAREN", "KURGUNG/SURUNGAI", "KABIYET", "NDALAT", "KABISAGA", "SANGALO/KEBULONIK"]
    },
    stations: ["KAPSABET"],
    localities: ["KAPSABET", "NANDI HILLS"],
    postalCodes: [{ code: "30300", town: "KAPSABET" }]
  },
  "BARINGO": {
    name: "BARINGO",
    subCounties: ["TIATY", "BARINGO NORTH", "BARINGO CENTRAL", "BARINGO SOUTH", "MOGOTIO", "ELDAMA RAVINE"],
    wards: {
      "TIATY": ["TIRIOKO", "KOLOWA", "RIBKWO", "SILALE", "LOIYAMOROCK", "TANGULBEI/KOROSSI", "CHURO/AMAYA"],
      "BARINGO NORTH": ["BARWESSA", "KABARTONJO", "SAIMO/KIPSARAMAN", "SAIMO/SOI", "BARTABWA"],
      "BARINGO CENTRAL": ["KABARNET", "SACHO", "TENGES", "EWALEL/CHAPCHAP", "KAPROPITA"],
      "BARINGO SOUTH": ["MARIGAT", "ILCHAMUS", "MOCHONGOI", "MUKUTANI"],
      "MOGOTIO": ["MOGOTIO", "EMINING", "KISANANA"],
      "ELDAMA RAVINE": ["LEMBUS", "LEMBUS KWEN", "RAVINE", "MUMBERES/MAJI MAZURI", "LEMBUS/PERKERRA", "KOIBATEK"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["KABARNET"],
    postalCodes: [{ code: "30400", town: "KABARNET" }]
  },
  "LAIKIPIA": {
    name: "LAIKIPIA",
    subCounties: ["LAIKIPIA WEST", "LAIKIPIA EAST", "LAIKIPIA NORTH"],
    wards: {
      "LAIKIPIA WEST": ["OL-MORAN", "RUMURUTI TOWNSHIP", "GITHIGA", "MARMANET", "IGWAMITI", "SALAMA"],
      "LAIKIPIA EAST": ["NGOBIT", "TIGITHI", "THINGITHU", "NANYUKI", "UMANDE"],
      "LAIKIPIA NORTH": ["SOSIAN", "SEGERA", "MUGOGODO WEST", "MUGOGODO EAST"]
    },
    stations: ["NANYUKI"],
    localities: ["NANYUKI", "RUMURUTI"],
    postalCodes: [{ code: "10400", town: "NANYUKI" }]
  },
  "NAKURU": {
    name: "NAKURU",
    subCounties: ["MOLO", "NJORO", "NAIVASHA", "GILGIL", "KURESOI SOUTH", "KURESOI NORTH", "SUBUKIA", "RONGAI", "BAHATI", "NAKURU TOWN WEST", "NAKURU TOWN EAST"],
    wards: {
      "MOLO": ["MARIASHONI", "ELBURGON", "TURI", "MOLO"],
      "NJORO": ["MAU NAROK", "MAUCHE", "KIHINGO", "NESSUIT", "LARE", "NJORO"],
      "NAIVASHA": ["BIASHARA", "HELLS GATE", "LAKE VIEW", "MAI MAHIU", "MAIELLA", "OLKARIA", "NAIVASHA EAST", "VIWANDANI"],
      "GILGIL": ["GILGIL", "ELEMENTAITA", "MBARUK/EBURU", "MALEWA WEST", "MURINDATI"],
      "KURESOI SOUTH": ["AMALO", "KERINGET", "KIPTAGICH", "TINET"],
      "KURESOI NORTH": ["KIPTORORO", "NYOTA", "SIRIKWA", "KAMARA"],
      "SUBUKIA": ["SUBUKIA", "WASEGES", "KABAZI"],
      "RONGAI": ["MENENGAI WEST", "SOIN", "VISOI", "MOSOP", "SOLAI"],
      "BAHATI": ["DUNDORI", "KABATINI", "KIAMAINA", "LANET/UMOJA", "BAHATI"],
      "NAKURU TOWN WEST": ["BARUT", "LONDON", "KAPTEMBWO", "KAPKURES", "RHODA", "SHAABAB"],
      "NAKURU TOWN EAST": ["BIASHARA", "KIVUMBINI", "FLAMINGO", "MENENGAI", "NAKURU EAST"]
    },
    stations: ["NAKURU", "NAIVASHA"],
    localities: ["NAKURU TOWN", "NAIVASHA"],
    postalCodes: [{ code: "20100", town: "NAKURU" }]
  },
  "NAROK": {
    name: "NAROK",
    subCounties: ["KILGORIS", "EMURUA DIKIRR", "NAROK NORTH", "NAROK EAST", "NAROK SOUTH", "NAROK WEST"],
    wards: {
      "KILGORIS": ["KILGORIS CENTRAL", "KEYIAN", "ANGATA BARIKOI", "SHANKOE", "KIMINTET", "LOLGORIAN"],
      "EMURUA DIKIRR": ["ILKERIN", "OLOLMASANI", "MOGONDO", "KAPSASIAN"],
      "NAROK NORTH": ["OLPUSIMORU", "OLOKURTO", "NAROK TOWN", "NKARETA", "OLORROPIL", "MELILI"],
      "NAROK EAST": ["MOSIRO", "ILDAMAT", "KEEKONYOKIE", "SUSWA"],
      "NAROK SOUTH": ["MAJIMOTO/NAROOSURA", "OLOLULUNG'A", "MELELO", "LOITA", "SOGOO", "SAGAMIAN"],
      "NAROK WEST": ["ILMOTIOK", "MARA", "SIANA", "NAIKARRA"]
    },
    stations: ["NAROK"],
    localities: ["NAROK TOWN"],
    postalCodes: [{ code: "20500", town: "NAROK" }]
  },
  "KAJIADO": {
    name: "KAJIADO",
    subCounties: ["KAJIADO NORTH", "KAJIADO CENTRAL", "KAJIADO EAST", "KAJIADO WEST", "KAJIADO SOUTH"],
    wards: {
      "KAJIADO NORTH": ["OLKERI", "ONGATA RONGAI", "NKAIMURUNYA", "OLOOLUA", "NGONG"],
      "KAJIADO CENTRAL": ["PURKO", "ILDAMAT", "DALALEKUTUK", "MATAPATO NORTH", "MATAPATO SOUTH"],
      "KAJIADO EAST": ["KAPUTIEI NORTH", "KITENGELA", "OLOOSIRKON/SHOLINKE", "KENYAWA-POKA", "IMARORO"],
      "KAJIADO WEST": ["KEEKONYOKIE", "ILOODOKILANI", "MAGADI", "EWUASO OONKIDONG'I", "MOSIRO"],
      "KAJIADO SOUTH": ["ENTONET/LENKISIM", "MBIRIKANI/ESELENKEI", "KUKU", "ROMBO", "KIMANA"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["KITENGELA", "NGONG", "KAJIADO"],
    postalCodes: [{ code: "01100", town: "KAJIADO" }]
  },
  "KERICHO": {
    name: "KERICHO",
    subCounties: ["KIPKELION EAST", "KIPKELION WEST", "AINAMOI", "BURETI", "BELGUT", "SIGOWET/SOIN"],
    wards: {
      "KIPKELION EAST": ["LONDIANI", "KEDOWA/KIMUGUL", "CHEPSEON", "TENDENO/SORGET"],
      "KIPKELION WEST": ["KUNYAK", "KAMASIAN", "KIPKELION", "CHILCHILA"],
      "AINAMOI": ["KAPSOIT", "AINAMOI", "KAPKUGERWET", "KIPCHEBOR", "KIPCHIMCHIM", "KAPSAOS"],
      "BURETI": ["KISIARA", "TEBESONIK", "CHEBOIN", "CHEMOSOT", "LITEIN", "CHEPLANGET", "KAPKATET"],
      "BELGUT": ["WALDAI", "KABIANGA", "CHEPTORORIET/SERETUT", "CHAIK", "KAPSUSER"],
      "SIGOWET/SOIN": ["SIGOWET", "KAPLELARTET", "SOLIAT", "SOIN"]
    },
    stations: ["KERICHO"],
    localities: ["KERICHO TOWN"],
    postalCodes: [{ code: "20200", town: "KERICHO" }]
  },
  "BOMET": {
    name: "BOMET",
    subCounties: ["SOTIK", "CHEPALUNGU", "BOMET EAST", "BOMET CENTRAL", "KONOIN"],
    wards: {
      "SOTIK": ["NDANAI/ABOSI", "CHEMAGEL", "KIPSONOI", "KAPLETUNDO", "RONGENA/MANARET"],
      "CHEPALUNGU": ["KONG'ASIS", "NYANGORES", "SIGOR", "CHEBUNYO", "SIONGIROI"],
      "BOMET EAST": ["MERIGI", "KEMBU", "LONGISA", "KIPRERES", "CHEMANER"],
      "BOMET CENTRAL": ["SILIBWET TOWNSHIP", "NDARAWETA", "SINGORWET", "CHESOEN", "MUTARAKWA"],
      "KONOIN": ["CHEPCHABAS", "KIMULOT", "MOGOGOSIEK", "BOITO", "EMBOMOS"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["BOMET TOWN"],
    postalCodes: [{ code: "20400", town: "BOMET" }]
  },
  "KAKAMEGA": {
    name: "KAKAMEGA",
    subCounties: ["LUGARI", "LIKUYANI", "MALAVA", "LURAMBI", "NAVAKHOLO", "MUMIAS WEST", "MUMIAS EAST", "MATUNGU", "BUTERE", "KHWISERO", "SHINYALU", "IKOLOMANI"],
    wards: {
      "LUGARI": ["MAUTUMA", "LUGARI", "LUMAKANDA", "CHEKALINI", "CHEVAYWA", "LWANDETI"],
      "LIKUYANI": ["LIKUYANI", "SANGO", "KONGONI", "NZOIA", "SINOKO"],
      "MALAVA": ["WEST KABRAS", "CHEMUCHE", "EAST KABRAS", "BUTALI/CHEGULO", "MANDA-SHIVANGA", "SHIRUGU-MUGAI", "SOUTH KABRAS"],
      "LURAMBI": ["BUTSOTSO EAST", "BUTSOTSO SOUTH", "BUTSOTSO CENTRAL", "SHEYWE", "MAHIAKALO", "SHIRERE"],
      "NAVAKHOLO": ["INGOSTSE-MATHIA", "SHINOYI-SHIKOMARI-ESUMEYIA", "BUNYALA WEST", "BUNYALA EAST", "BUNYALA CENTRAL"],
      "MUMIAS WEST": ["MUMIAS CENTRAL", "MUMIAS NORTH", "ETENJE", "MUSANDA"],
      "MUMIAS EAST": ["LUSHEYA/LUBINU", "MALAHA/ISONGO/MAKUNGA", "EAST WANGA"],
      "MATUNGU": ["KOYONZO", "KHOLERA", "KHALABA", "MAYONI", "NAMAMALI"],
      "BUTERE": ["MARAMA WEST", "MARAMA CENTRAL", "MARENYO - SHIANDA", "MARAMA NORTH", "MARAMA SOUTH"],
      "KHWISERO": ["KISA NORTH", "KISA EAST", "KISA WEST", "KISA CENTRAL"],
      "SHINYALU": ["ISUKHA NORTH", "MURHANDA", "ISUKHA CENTRAL", "ISUKHA SOUTH", "ISUKHA EAST", "ISUKHA WEST"],
      "IKOLOMANI": ["IDAKHO SOUTH", "IDAKHO EAST", "IDAKHO NORTH", "IDAKHO CENTRAL"]
    },
    stations: ["KAKAMEGA"],
    localities: ["KAKAMEGA TOWN", "MUMIAS"],
    postalCodes: [{ code: "50100", town: "KAKAMEGA" }]
  },
  "VIHIGA": {
    name: "VIHIGA",
    subCounties: ["VIHIGA", "SABATIA", "HAMISI", "LUANDA", "EMUHAYA"],
    wards: {
      "VIHIGA": ["LUGAGA-WAMULUMA", "SOUTH MARAGOLI", "CENTRAL MARAGOLI", "MUNGOMA"],
      "SABATIA": ["LYADUYWA/IZAVA", "WEST SABATIA", "CHAVAKALI", "NORTH MARAGOLI", "WODANGA", "BUSALI"],
      "HAMISI": ["SHIRU", "GISAMBAI", "SHAMAKHOKHO", "BANJA", "MUHUDU", "TAMBUA", "JEPKOYAI"],
      "LUANDA": ["LUANDA TOWNSHIP", "WEMILABI", "MWIBONA", "LUANDA SOUTH", "EMABUNGO"],
      "EMUHAYA": ["NORTH EAST BUNYORE", "CENTRAL BUNYORE", "WEST BUNYORE"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["VIHIGA TOWN"],
    postalCodes: [{ code: "50300", town: "MARAGOLI" }]
  },
  "BUNGOMA": {
    name: "BUNGOMA",
    subCounties: ["MT. ELGON", "SIRISIA", "KABUCHAI", "BUMULA", "KANDUYI", "WEBUYE EAST", "WEBUYE WEST", "KIMILILI", "TONGAREN"],
    wards: {
      "MT. ELGON": ["CHEPTAIS", "CHESIKAKI", "CHEPYUK", "KAPKATENY", "KAPTAMA", "ELGON"],
      "SIRISIA": ["NAMWELA", "MALAKISI/SOUTH KULISIRU", "LWANDANYI"],
      "KABUCHAI": ["KABUCHAI/CHWELE", "WEST NALONDO", "BWAKE/LUUYA", "MUKUYUNI"],
      "BUMULA": ["SOUTH BUKUSU", "BUMULA", "KHASOKO", "KABULA", "KIMAETI", "WEST BUKUSU", "SIBOTI"],
      "KANDUYI": ["BUKEMBE WEST", "BUKEMBE EAST", "TOWNSHIP", "KHALABA", "MUSIKOMA", "EAST SANG'ALO", "MARAKARU/TUUTI", "WEST SANG'ALO"],
      "WEBUYE EAST": ["MIHUU", "NDIVISI", "MARAKA"],
      "WEBUYE WEST": ["MISIKHU", "SITIKHO", "MATULO", "BOKOLI"],
      "KIMILILI": ["KIBINGEI", "KIMILILI", "MAENI", "KAMUKUYWA"],
      "TONGAREN": ["MBAKALO", "NAITIRI/KABUYEFWE", "MILIMA", "NDALU/ TABANI", "TONGAREN", "SOYSAMBU/ MITUA"]
    },
    stations: ["BUNGOMA"],
    localities: ["BUNGOMA TOWN", "WEBUYE"],
    postalCodes: [{ code: "50200", town: "BUNGOMA" }]
  },
  "BUSIA": {
    name: "BUSIA",
    subCounties: ["TESO NORTH", "TESO SOUTH", "NAMBALE", "MATAYOS", "BUTULA", "FUNYULA", "BUDALANGI"],
    wards: {
      "TESO NORTH": ["MALABA CENTRAL", "MALABA NORTH", "ANG'URAI SOUTH", "ANG'URAI NORTH", "ANG'URAI EAST", "MALABA SOUTH"],
      "TESO SOUTH": ["ANG'OROM", "CHAKOL SOUTH", "CHAKOL NORTH", "AMUKURA WEST", "AMUKURA EAST", "AMUKURA CENTRAL"],
      "NAMBALE": ["NAMBALE TOWNSHIP", "BUKHAYO NORTH/WALTSI", "BUKHAYO EAST", "BUKHAYO CENTRAL"],
      "MATAYOS": ["BUKHAYO WEST", "MAYENJE", "MATAYOS SOUTH", "BUSIBWABO", "BURUMBA"],
      "BUTULA": ["MARACHI WEST", "KINGANDOLE", "MARACHI CENTRAL", "MARACHI EAST", "MARACHI NORTH", "ELUGULU"],
      "FUNYULA": ["NAMBOBOTO NAMBUKU", "NANGINA", "AGENG'A NANGUBA", "BWIRI"],
      "BUDALANGI": ["BUNYALA CENTRAL", "BUNYALA NORTH", "BUNYALA WEST", "BUNYALA SOUTH"]
    },
    stations: ["BUSIA"],
    localities: ["BUSIA TOWN"],
    postalCodes: [{ code: "50400", town: "BUSIA" }]
  },
  "SIAYA": {
    name: "SIAYA",
    subCounties: ["UGENYA", "UGUNJA", "ALEGO USONGA", "GEM", "BONDO", "RARIEDA"],
    wards: {
      "UGENYA": ["WEST UGENYA", "UKWALA", "NORTH UGENYA", "EAST UGENYA"],
      "UGUNJA": ["SIDINDI", "SIGOMERE", "UGUNJA"],
      "ALEGO USONGA": ["USONGA", "WEST ALEGO", "CENTRAL ALEGO", "SIAYA TOWNSHIP", "NORTH ALEGO", "SOUTH EAST ALEGO"],
      "GEM": ["NORTH GEM", "WEST GEM", "CENTRAL GEM", "YALA TOWNSHIP", "EAST GEM", "SOUTH GEM"],
      "BONDO": ["WEST YIMBO", "CENTRAL SAKWA", "SOUTH SAKWA", "YIMBO EAST", "WEST SAKWA", "NORTH SAKWA"],
      "RARIEDA": ["EAST ASEMBO", "WEST ASEMBO", "NORTH UYOMA", "SOUTH UYOMA", "WEST UYOMA"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["SIAYA TOWN", "BONDO"],
    postalCodes: [{ code: "40600", town: "SIAYA" }]
  },
  "KISUMU": {
    name: "KISUMU",
    subCounties: ["KISUMU EAST", "KISUMU WEST", "KISUMU CENTRAL", "SEME", "NYANDO", "MUHORONI", "NYAKACH"],
    wards: {
      "KISUMU EAST": ["KAJULU", "KOLWA EAST", "MANYATTA 'B'", "NYALENDA 'A'", "KOLWA CENTRAL"],
      "KISUMU WEST": ["SOUTH WEST KISUMU", "CENTRAL KISUMU", "KISUMU NORTH", "WEST KISUMU", "NORTH WEST KISUMU"],
      "KISUMU CENTRAL": ["RAILWAYS", "MIGOSI", "SHAURIMOYO KALOLENI", "MARKET MILIMANI", "KONDELE", "NYALENDA B"],
      "SEME": ["WEST SEME", "CENTRAL SEME", "EAST SEME", "NORTH SEME"],
      "NYANDO": ["EAST KANO/WAWIDHI", "AWASI/ONJIKO", "AHERO", "KABONYO/KANYAGWAL", "KOBURA"],
      "MUHORONI": ["MIWANI", "OMBEYI", "MASOGO/NYANG'OMA", "CHEMELIL", "MUHORONI/KORU"],
      "NYAKACH": ["SOUTH WEST NYAKACH", "NORTH NYAKACH", "CENTRAL NYAKACH", "WEST NYAKACH", "SOUTH EAST NYAKACH"]
    },
    stations: ["KISUMU"],
    localities: ["KISUMU CITY"],
    postalCodes: [{ code: "40100", town: "KISUMU" }]
  },
  "HOMA BAY": {
    name: "HOMA BAY",
    subCounties: ["KASIPUL", "KABONDO KASIPUL", "KARACHUONYO", "RANGWE", "HOMA BAY TOWN", "NDHIWA", "SUBA NORTH", "SUBA SOUTH"],
    wards: {
      "KASIPUL": ["WEST KASIPUL", "SOUTH KASIPUL", "CENTRAL KASIPUL", "EAST KAMAGAK", "WEST KAMAGAK"],
      "KABONDO KASIPUL": ["KABONDO EAST", "KABONDO WEST", "KOKWANYO/KAKELO", "KOJWACH"],
      "KARACHUONYO": ["WEST KARACHUONYO", "NORTH KARACHUONYO", "CENTRAL", "KANYALUO", "KIBIRI", "WANGCHIENG", "KENDU BAY TOWN"],
      "RANGWE": ["WEST GEM", "EAST GEM", "KAGAN", "KOCHIA"],
      "HOMA BAY TOWN": ["HOMA BAY CENTRAL", "HOMA BAY ARUJO", "HOMA BAY WEST", "HOMA BAY EAST"],
      "NDHIWA": ["KWABWAI", "KANYADOTO", "KANYIKELA", "KABUOCH NORTH", "KABUOCH SOUTH/PALA", "KANYAMWA KOLOGI", "KANYAMWA KOSEWE"],
      "SUBA NORTH": ["MFANGANO ISLAND", "RUSINGA ISLAND", "KASGUNGA", "GEMBE", "LAMBWE"],
      "SUBA SOUTH": ["GWASSI SOUTH", "GWASSI NORTH", "KAKSINGRI WEST", "RUMA-KAKSINGRI"]
    },
    stations: ["HOMA BAY"],
    localities: ["HOMA BAY TOWN"],
    postalCodes: [{ code: "40300", town: "HOMA BAY" }]
  },
  "MIGORI": {
    name: "MIGORI",
    subCounties: ["RONGO", "AWENDO", "SUNA EAST", "SUNA WEST", "URIRI", "NYATIKE", "KURIA WEST", "KURIA EAST"],
    wards: {
      "RONGO": ["NORTH KAMAGAMBO", "CENTRAL KAMAGAMBO", "EAST KAMAGAMBO", "SOUTH KAMAGAMBO"],
      "AWENDO": ["NORTH SAKWA", "SOUTH SAKWA", "WEST SAKWA", "CENTRAL SAKWA"],
      "SUNA EAST": ["GOD JOPE", "SUNA CENTRAL", "KAKRAO", "KWA"],
      "SUNA WEST": ["WIGA", "WASWETA II", "RAGANA-ORUBA", "WASIMBETE"],
      "URIRI": ["WEST KANYAMKAGO", "NORTH KANYAMKAGO", "CENTRAL KANYAMKAGO", "SOUTH KANYAMKAGO", "EAST KANYAMKAGO"],
      "NYATIKE": ["KACHIEN'G", "KANYASA", "NORTH KADEM", "MACALDER/KANYARWANDA", "KALER", "GOT KACHOLA", "MUHURU"],
      "KURIA WEST": ["BUKIRA EAST", "BUKIRA CENTRL/IKEREGE", "ISIBANIA", "MAKERERO", "MASABA", "TAGARE", "NYAMOSENSE/KOMOSOKO"],
      "KURIA EAST": ["GOKEHARAKA/GETAMBWEGA", "NTIMARU WEST", "NTIMARU EAST", "NYABASI EAST", "NYABASI WEST"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["MIGORI TOWN"],
    postalCodes: [{ code: "40400", town: "SUNA" }]
  },
  "KISII": {
    name: "KISII",
    subCounties: ["BONCHARI", "SOUTH MUGIRANGO", "BOMACHOGE BORABU", "BOBASI", "BOMACHOGE CHACHE", "NYARIBARI MASABA", "NYARIBARI CHACHE", "KITUTU CHACHE NORTH", "KITUTU CHACHE SOUTH"],
    wards: {
      "BONCHARI": ["BOMARIBA", "BOGIAKUMU", "BOMORENDA", "RIANA"],
      "SOUTH MUGIRANGO": ["TABAKA", "BOIKANG'A", "BOGETENGA", "BORABU / CHITAGO", "MOTICHO", "GETENGA"],
      "BOMACHOGE BORABU": ["BOMBABA BORABU", "BOOCHI BORABU", "BOKIMONGE", "MAGENCHE"],
      "BOBASI": ["MASIGE WEST", "MASIGE EAST", "BASI CENTRAL", "NYACHEKI", "BASI BOGETAORIO", "BOBASI CHACHE", "SAMETA/MOKWERERO", "BOBASI BOITANGARE"],
      "BOMACHOGE CHACHE": ["MAJOGE BASI", "BOOCHI/TENDERE", "BOSOTI/SENGERA"],
      "NYARIBARI MASABA": ["ICHUNI", "NYAMASIBI", "MASIMBA", "GESUSU", "KIAMOKAMA"],
      "NYARIBARI CHACHE": ["BOBARACHO", "KISII CENTRAL", "KEUMBU", "KIOGORO", "BIRONGO", "IBENO"],
      "KITUTU CHACHE NORTH": ["MONYERERO", "SENSI", "MARANI", "KEGOGI"],
      "KITUTU CHACHE SOUTH": ["BOGUSERO", "BOGEKA", "NYAKOE", "KITUTU CENTRAL", "NYATIEKO"]
    },
    stations: ["KISII"],
    localities: ["KISII TOWN"],
    postalCodes: [{ code: "40200", town: "KISII" }]
  },
  "NYAMIRA": {
    name: "NYAMIRA",
    subCounties: ["KITUTU MASABA", "WEST MUGIRANGO", "NORTH MUGIRANGO", "BORABU"],
    wards: {
      "KITUTU MASABA": ["RIGOMA", "GACHUBA", "KEMERA", "MAGOMBO", "MANGA", "GESIMA"],
      "WEST MUGIRANGO": ["NYAMAIYA", "BOGICHORA", "BOSAMARO", "BONYAMATUTA", "TOWNSHIP"],
      "NORTH MUGIRANGO": ["ITIBO", "BOMWAGAMO", "BOKEIRA", "MAGWAGWA", "EKERENYO"],
      "BORABU": ["MEKENENE", "KIABONYORU", "NYANSIONGO", "ESISE"]
    },
    stations: ["LOCAL KRA OFFICE"],
    localities: ["NYAMIRA TOWN"],
    postalCodes: [{ code: "40500", town: "NYAMIRA" }]
  }
};

export const COUNTIES = Object.keys(KENYA_ADMIN_DATA).sort();

export const GET_SUB_COUNTIES = (county: string) => KENYA_ADMIN_DATA[county]?.subCounties || ["OTHER"];
export const GET_STATIONS = (county: string) => KENYA_ADMIN_DATA[county]?.stations || ["LOCAL KRA OFFICE"];
export const GET_LOCALITIES = (county: string, subCounty?: string) => {
  if (subCounty && KENYA_ADMIN_DATA[county]?.wards[subCounty]) {
    return KENYA_ADMIN_DATA[county].wards[subCounty];
  }
  return KENYA_ADMIN_DATA[county]?.localities || ["TOWN CENTRE"];
};
export const GET_POSTAL_CODES = (county: string) => KENYA_ADMIN_DATA[county]?.postalCodes || [{ code: "00100", town: "NAIROBI GPO" }];
